{{- if eq .Values.configXml.existingSecret "" }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "radarr.fullname" . }}-xml
  namespace: {{ .Values.namespace }}
  labels:
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/name: radarr
    {{- include "radarr.labels" . | nindent 4 }}
type: Opaque
data:
  config.xml: {{ include "radarr.configXml" . | b64enc }}
{{- end }}
