{{- range $key, $value := .Values.persistence }}
{{- if and $value.enabled (eq $value.type "pvc") (empty $value.existingClaim) }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ printf "%s-%s" (include "radarr.fullname" $) $key }}
  namespace: {{ $.Release.Namespace }}
  labels:
    # Include standard labels defined in _helpers
{{ include "radarr.labels" $ | indent 4 }}
    # Include extra labels defined globally in values.yaml
{{- range $labelKey, $labelValue := $.Values.extraLabels }}
    {{ $labelKey }}: {{ $labelValue | quote }}
{{- end }}
spec:
  accessModes:
    {{- toYaml $value.accessModes | nindent 4 }}
  {{- if $value.storageClass }}
  storageClassName: {{ $value.storageClass | quote }}
  {{- end }}
  resources:
    requests:
      storage: {{ $value.size | quote }}
---
{{- end }}
{{- end }}
