{{- /* Render DaemonSet only if workloadType is 'daemonset' */}}
{{- if eq .Values.workloadType "daemonset" -}}
apiVersion: {{ include "common.daemonset.apiVersion" . }}
kind: DaemonSet
metadata:
  name: {{ include "common.fullname" . }}
  labels:
    {{- include "common.labels" . | nindent 4 }}
  {{- with (merge .Values.podAnnotations .Values.commonAnnotations) }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  selector:
    matchLabels:
      {{- include "common.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with (merge .Values.podAnnotations .Values.commonAnnotations) }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "common.selectorLabels" . | nindent 8 }}
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.initContainers }}
      initContainers:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "common.serviceAccountName" . }}
      {{- with .Values.podSecurityContext }}
      securityContext:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- if .Values.terminationGracePeriodSeconds }}
      terminationGracePeriodSeconds: {{ .Values.terminationGracePeriodSeconds }}
      {{- end }}
      {{- if .Values.dnsPolicy }}
      dnsPolicy: {{ .Values.dnsPolicy }}
      {{- end }}
      # hostNetwork: false # Set to true if the pod needs host network access
      # hostPID: false # Set to true if the pod needs access to the host PID namespace
      containers:
        - name: {{ .Chart.Name }}
          {{- with .Values.securityContext }}
          securityContext:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default "" }}" # Use default tag "" if not specified, appVersion removed from library
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            {{- /* Define container ports based on the containerPorts list in values */}}
            {{- range .Values.containerPorts }}
        - name: {{ .name }}
          persistentVolumeClaim:
            {{- /* Use existingClaim name if provided, otherwise generate the name */}}
            claimName: {{ .existingClaim | default (printf "%s-%s" (include "common.fullname" $) .name) }}
        {{- end }}
        {{- end }}
          {{- with .Values.env }}
          env:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.envFrom }}
          envFrom:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- if .Values.livenessProbe.enabled }}
          livenessProbe:
            {{- /* Ensure probe port references a defined container port name if applicable */}}
            {{- $probe := deepCopy .Values.livenessProbe }}
            {{- $enabled := unset $probe "enabled" }}
            {{- toYaml $probe | nindent 12 }}
          {{- end }}
          {{- if .Values.readinessProbe.enabled }}
          readinessProbe:
            {{- /* Ensure probe port references a defined container port name if applicable */}}
            {{- $probe := deepCopy .Values.readinessProbe }}
            {{- $enabled := unset $probe "enabled" }}
            {{- toYaml $probe | nindent 12 }}
          {{- end }}
          {{- if .Values.startupProbe.enabled }}
          startupProbe:
            {{- /* Ensure probe port references a defined container port name if applicable */}}
            {{- $probe := deepCopy .Values.startupProbe }}
            {{- $enabled := unset $probe "enabled" }}
            {{- toYaml $probe | nindent 12 }}
          {{- end }}
          {{- with .Values.command }}
          command:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.args }}
          args:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.lifecycle }}
          lifecycle:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            {{- /* Mount volumes defined in .Values.volumeMounts */}}
            {{- with .Values.volumeMounts }}
            {{- toYaml . | nindent 12 }}
            {{- end }}
            {{- /* Mount PVCs defined in .Values.persistence.claims */}}
            {{- if .Values.persistence.enabled }}
            {{- range .Values.persistence.claims }}
            - name: {{ .name }}
              mountPath: {{ .mountPath }} # User must define mountPath for each claim in values.yaml
              {{- if .subPath }}
              subPath: {{ .subPath }}
              {{- end }}
              {{- if .readOnly }}
              readOnly: {{ .readOnly }}
              {{- end }}
            {{- end }}
            {{- end }}
      volumes:
        {{- /* Add volumes defined in .Values.volumes */}}
        {{- with .Values.volumes }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
        {{- /* Add volumes for PVCs defined in .Values.persistence.claims */}}
        {{- if .Values.persistence.enabled }}
        {{- range .Values.persistence.claims }}
        - name: {{ .name }}
          persistentVolumeClaim:
            {{- /* Use existingClaim name if provided, otherwise generate the name */}}
            claimName: {{ .existingClaim | default (printf "%s-%s" (include "common.fullname" $) .name) }}
        {{- end }}
        {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      # Use daemonset specific tolerations if defined, otherwise fall back to common tolerations
      {{- with coalesce .Values.daemonset.tolerations .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
  {{- with .Values.daemonset.updateStrategy }}
  updateStrategy:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
