{{- /* Check if Gateway API HTTPRoute is enabled */}}
{{- if and .Values.gatewayApi.enabled .Values.gatewayApi.httpRoute.enabled -}}
{{- $fullName := include "common.fullname" . -}}
apiVersion: {{ include "common.gatewayapi.httproute.apiVersion" . }}
kind: HTTPRoute
metadata:
  name: {{ default $fullName .Values.gatewayApi.httpRoute.name }}
  labels:
    {{- include "common.labels" . | nindent 4 }}
    {{- with .Values.gatewayApi.httpRoute.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- with (merge .Values.gatewayApi.httpRoute.annotations .Values.commonAnnotations) }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- with .Values.gatewayApi.httpRoute.parentRefs }}
  parentRefs:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with .Values.gatewayApi.httpRoute.hostnames }}
  hostnames:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  rules:
    {{- range .Values.gatewayApi.httpRoute.rules }}
    - matches:
        {{- with .matches }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      {{- with .filters }}
      filters:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      backendRefs:
        {{- range .backendRefs }}
        {{- /* Check if a backend service name is specified */}}
        {{- if .name }}
        - name: {{ $fullName }}-{{ .name }} {{/* Construct target service name */}}
          port: {{ .port }} {{/* Port number is required for backendRefs */}}
          {{- with .weight }}
          weight: {{ . }}
          {{- end }}
          # Add other backendRef fields as needed (e.g., filters)
        {{- else }}
          {{- /* Backend ignored if name is missing */}}
          {{- /* You might want to log a warning here using tpl function if needed */}}
        {{- end }} {{- /* End if .name */}}
        {{- end }} {{- /* End range .backendRefs */}}
    {{- end }} {{- /* End range .Values.gatewayApi.httpRoute.rules */}}
{{- end }} {{- /* End if gatewayApi.enabled and httpRoute.enabled */}}
