{{- /* Check if ingress is enabled */}}
{{- if .Values.ingress.enabled -}}
{{- $fullName := include "common.fullname" . -}}
apiVersion: {{ include "common.ingress.apiVersion" . }}
kind: Ingress
metadata:
  name: {{ $fullName }}
  labels:
    {{- include "common.labels" . | nindent 4 }}
  {{- with (merge .Values.ingress.annotations .Values.commonAnnotations) }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- if and (.Values.ingress.className) (semverCompare ">=1.18-0" .Capabilities.KubeVersion.GitVersion) }}
  ingressClassName: {{ .Values.ingress.className }}
  {{- end }}
  {{- if .Values.ingress.tls }}
  tls:
    {{- range .Values.ingress.tls }}
    - hosts:
        {{- range .hosts }}
        - {{ . | quote }}
        {{- end }}
      secretName: {{ .secretName }}
    {{- end }}
  {{- end }}
  rules:
    {{- range .Values.ingress.hosts }}
    - host: {{ .host | quote }}
      http:
        paths:
          {{- range .paths }}
          {{- /* Check if a backend service name is specified for this path */}}
          {{- if .backend.service.name }}
          - path: {{ .path }}
            {{- if and .pathType (semverCompare ">=1.18-0" $.Capabilities.KubeVersion.GitVersion) }}
            pathType: {{ .pathType }}
            {{- end }}
            backend:
              {{- if semverCompare ">=1.19-0" $.Capabilities.KubeVersion.GitVersion }}
              service:
                {{- /* Construct the target service name: <fullname>-<serviceNameFromValues> */}}
                name: {{ $fullName }}-{{ .backend.service.name }}
                port:
                  {{- if .backend.service.port.name }}
                  name: {{ .backend.service.port.name }}
                  {{- else if .backend.service.port.number }}
                  number: {{ .backend.service.port.number }}
                  {{- else }}
                    {{- /* Error or default needed if neither name nor number is specified */}}
                    {{- fail "Ingress backend service port requires either 'name' or 'number'" -}}
                  {{- end }}
              {{- else }}
              serviceName: {{ $fullName }}-{{ .backend.service.name }}
              servicePort: {{ .backend.service.port.name | default .backend.service.port.number }}
              {{- end }}
          {{- else }}
            {{- /* Path ignored if backend service name is missing */}}
            {{- /* You might want to log a warning here using tpl function if needed */}}
          {{- end }} {{- /* End if .backend.service.name */}}
          {{- end }} {{- /* End range .paths */}}
    {{- end }} {{- /* End range .Values.ingress.hosts */}}
{{- end }} {{- /* End if .Values.ingress.enabled */}}
