# ------------------------------------------------------------------------------
# Name and fullname override
# ------------------------------------------------------------------------------
# nameOverride: ""
# fullnameOverride: ""

# ------------------------------------------------------------------------------
# Namespace
# ------------------------------------------------------------------------------
namespace: default

# ------------------------------------------------------------------------------
# Image configuration
# ------------------------------------------------------------------------------
image:
  repository: lscr.io/linuxserver/sonarr
  tag: latest
  pullPolicy: IfNotPresent

# ------------------------------------------------------------------------------
# Number of replicas
# ------------------------------------------------------------------------------
replicaCount: 1

# ------------------------------------------------------------------------------
# Labels
# ------------------------------------------------------------------------------
labels: {}

# ------------------------------------------------------------------------------
# Environment variables (UMASK, etc.)
# ------------------------------------------------------------------------------
env:
  UMASK: "000"

# ------------------------------------------------------------------------------
# Liveness probe
# ------------------------------------------------------------------------------
livenessProbe:
  enabled: true
  initialDelaySeconds: 30
  periodSeconds: 60
  command: |
    curl --fail localhost:8989/api/v3/system/status?apiKey=`IFS=\> && while read -d \< E C; do if [[ $E = "ApiKey" ]]; then echo $C; fi; done < /config/config.xml`

# ------------------------------------------------------------------------------
# Service config
# ------------------------------------------------------------------------------
service:
  type: ClusterIP
  port: 8989

# ------------------------------------------------------------------------------
# Resource requests & limits
# ------------------------------------------------------------------------------
resources:
  limits:
    memory: 4Gi
  requests:
    cpu: 50m
    memory: 256Mi

# ------------------------------------------------------------------------------
# Node scheduling
# ------------------------------------------------------------------------------
nodeSelector: {}
tolerations: []
affinity: {}

# ------------------------------------------------------------------------------
# Persistence for Sonarr config
# ------------------------------------------------------------------------------
persistence:
  config:
    enabled: true
    size: 1Gi
    existingClaim: ""
    storageClass: ""

# ------------------------------------------------------------------------------
# NFS volume for media
# ------------------------------------------------------------------------------
nfs:
  enabled: true
  server: "10.3.200.151"
  path: "/mnt/zpool/plexmedia"

# ------------------------------------------------------------------------------
# Hostname override
# ------------------------------------------------------------------------------
hostname: sonarr

# ------------------------------------------------------------------------------
# configXml: Template-driven config.xml
# ------------------------------------------------------------------------------
configXml:
  # If non-empty, references an existing secret with a key "config.xml";
  # otherwise the chart will create a secret containing rendered config.xml.
  existingSecret: ""

  bindAddress: "*"
  port: 8989
  sslPort: 9898
  enableSsl: "False"
  launchBrowser: "True"
  apiKey: "xxxxxxxxxxx"
  authenticationMethod: "External"
  authenticationRequired: "DisabledForLocalAddresses"
  branch: "main"
  logLevel: "info"
  sslCertPath: ""
  sslCertPassword: ""
  urlBase: ""
  instanceName: "Sonarr"
  updateMechanism: "Docker"

  postgres:
    enabled: false
    user: ""
    password: ""
    host: ""
    port: 5432
    mainDb: ""
    logDb: ""
