apiVersion: v2
name: overseerr
description: A Helm chart to deploy Overseerr - a request management and media discovery tool for the Plex ecosystem
type: application
version: 0.1.0
appVersion: "latest"
