# ------------------------------------------------------------------------------
# Name and fullname override
# ------------------------------------------------------------------------------
# nameOverride: ""
# fullnameOverride: ""

# ------------------------------------------------------------------------------
# Namespace
# ------------------------------------------------------------------------------
namespace: webapps

# ------------------------------------------------------------------------------
# Image configuration
# ------------------------------------------------------------------------------
image:
  repository: lscr.io/linuxserver/overseerr
  tag: latest
  pullPolicy: Always

# ------------------------------------------------------------------------------
# Number of replicas
# ------------------------------------------------------------------------------
replicaCount: 1

# ------------------------------------------------------------------------------
# Labels
# ------------------------------------------------------------------------------
labels: {}

# ------------------------------------------------------------------------------
# Environment variables
# ------------------------------------------------------------------------------
env:
  TZ: Europe/London

# ------------------------------------------------------------------------------
# Liveness probe
# ------------------------------------------------------------------------------
livenessProbe:
  enabled: true
  initialDelaySeconds: 30
  periodSeconds: 60
  command: curl --fail localhost:5055

# ------------------------------------------------------------------------------
# Service config
# ------------------------------------------------------------------------------
service:
  type: ClusterIP
  port: 5055

# ------------------------------------------------------------------------------
# Resource requests & limits
# ------------------------------------------------------------------------------
resources:
  limits:
    memory: 512Mi
  requests:
    cpu: 500m
    memory: 258Mi

# ------------------------------------------------------------------------------
# Node scheduling
# ------------------------------------------------------------------------------
nodeSelector: {}
tolerations: []
affinity: {}

# ------------------------------------------------------------------------------
# Security context
# ------------------------------------------------------------------------------
securityContext:
  allowPrivilegeEscalation: false

# ------------------------------------------------------------------------------
# Storage configuration
# ------------------------------------------------------------------------------
storage:
  # Set to true to use iSCSI for /config instead of PVC
  useIscsi: false

# ------------------------------------------------------------------------------
# Persistence for Overseerr config (used when storage.useIscsi is false)
# ------------------------------------------------------------------------------
persistence:
  config:
    enabled: true
    size: 1Gi
    existingClaim: ""
    storageClass: ""

# ------------------------------------------------------------------------------
# NFS volume for backups
# ------------------------------------------------------------------------------
nfs:
  enabled: false
  server: ""
  path: ""

# ------------------------------------------------------------------------------
# iSCSI volume configuration (used when storage.useIscsi is true)
# ------------------------------------------------------------------------------
iscsi:
  enabled: false
  targetPortal: ""
  portals: []
  iqn: ""
  lun: 0
  fsType: "ext4"
  readOnly: false

# ------------------------------------------------------------------------------
# Hostname override
# ------------------------------------------------------------------------------
hostname: overseerr
