# Chart Releaser configuration
# See: https://github.com/helm/chart-releaser

# Specify the index path
index-path: .cr-index/index.yaml

# Chart repository URL prefix
chart-repo-url: https://tomf141.github.io/helmcharts/

# Skip existing chart versions
skip-existing: false

# Package chart dependencies
package-path: .cr-release-packages

# Release name template
release-name-template: "{{ .Name }}-{{ .Version }}"

# Release notes template
release-notes-template: |
  ## {{ .Name }} {{ .Version }}

  {{ if .Description }}{{ .Description }}{{ end }}

  {{ if .AppVersion }}App version: {{ .AppVersion }}{{ end }}
