# Chart Releaser configuration
# See: https://github.com/helm/chart-releaser

# Optional: Specify the index path (default: .cr-index/index.yaml)
index-path: .cr-index/index.yaml

# Optional: Chart repository URL prefix (default: https://<owner>.github.io/<repo>)
# This is used to construct URLs for the index.yaml file
# If not specified, it defaults to https://<owner>.github.io/<repo>
# chart-repo-url: https://tomf141.github.io/helmcharts/

# Optional: Skip existing chart versions (default: true)
# If set to true, chart-releaser will not upload charts that already exist in the repository
skip-existing: false

# Optional: Package chart dependencies (default: true)
# If set to true, chart-releaser will package chart dependencies
package-path: .cr-release-packages

# Optional: Release name template (default: {{ .Name }}-{{ .Version }})
# This is used to construct the name of the release
release-name-template: "{{ .Name }}-{{ .Version }}"

# Optional: Release notes template (default: {{ .Name }} {{ .Version }})
# This is used to construct the release notes
release-notes-template: |
  ## {{ .Name }} {{ .Version }}

  {{ if .Description }}{{ .Description }}{{ end }}

  {{ if .AppVersion }}App version: {{ .AppVersion }}{{ end }}
