{{- if empty .Values.secretConfig.existingSecretName }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ printf "%s-config" (include "appname.fullname" .) }}
  namespace: {{ .Release.Namespace }}
  labels:
    helm.sh/chart: {{ include "appname.chart" . }}
    app.kubernetes.io/name: {{ include "appname.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    {{- if .Chart.AppVersion }}
    app.kubernetes.io/version: {{ .Chart.AppVersion | quote }}
    {{- end }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    # Include extra labels defined globally in values.yaml
{{- range $key, $value := .Values.extraLabels }}
    {{ $key }}: {{ $value | quote }}
{{- end }}
type: Opaque
data:
  # Use sabnzbd.ini as the key, matching the subPath in deployment.yaml
  sabnzbd.ini: {{ include "sabnzbd.configfile" . | b64enc }}
{{- end }}
