{{- if and .Values.persistence.download.enabled (eq .Values.persistence.download.existingClaim "") }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "qbittorrent.fullname" . }}-download
  namespace: {{ .Values.namespace }}
  labels:
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/name: qbittorrent
    {{- include "qbittorrent.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  {{- if .Values.persistence.download.storageClass }}
  storageClassName: {{ .Values.persistence.download.storageClass | quote }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.persistence.download.size | quote }}
{{- end }}
