{{- if empty .Values.secretConfig.existingSecretName }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ printf "%s-config" (include "appname.fullname" .) }}
  namespace: {{ .Release.Namespace }}
  labels:
    # Include standard labels defined in _helpers
{{ include "appname.labels" . | indent 4 }}
    # Include extra labels defined globally in values.yaml
{{- range $key, $value := .Values.extraLabels }}
    {{ $key }}: {{ $value | quote }}
{{- end }}
type: Opaque
data:
  # Placeholder: Ensure this key matches the volumeMounts.subPath in deployment.yaml
  # and the key expected by the application.
  config.yaml: |-
    {{- /*
        Placeholder: Replace this comment block with a call to a helper
        that renders the application's config file content based on
        .Values.appConfig and .Values.secretConfig, similar to the
        'autoscan.configYaml' helper.
        Example: {{ include "appname.configfile" . | b64enc }}
        Ensure the output is base64 encoded.
    */}}
    # Default placeholder content if no helper is defined
    # Ensure your application can handle an empty or default config,
    # or define a suitable default structure in values.yaml and a helper.
    {} | b64enc # Example: empty YAML object, base64 encoded
{{- end }}
