apiVersion: v1
kind: Service
metadata:
  name: {{ include "qbittorrent.fullname" . }}
  namespace: {{ .Values.namespace }}
  labels:
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/name: qbittorrent
    {{- include "qbittorrent.labels" . | nindent 4 }}
spec:
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: "{{ .Values.service.port }}"
    port: {{ .Values.service.port }}
    targetPort: 8080
  selector:
    io.kompose.service: qbittorrent
  type: {{ .Values.service.type }}
