{{- if and .Values.persistence.conf.enabled (eq .Values.persistence.conf.existingClaim "") }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "autoscan.fullname" . }}-conf
  namespace: {{ .Values.namespace }}
  labels:
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/name: autoscan
    {{- include "autoscan.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
{{- if .Values.persistence.conf.storageClass }}
  storageClassName: {{ .Values.persistence.conf.storageClass | quote }}
{{- end }}
  resources:
    requests:
      storage: {{ .Values.persistence.conf.size | quote }}
{{- end }}
