{{- if empty .Values.secretConfig.existingSecretName }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ printf "%s-config" (include "autoscan.fullname" .) }}
  namespace: {{ .Release.Namespace }}
  labels:
    helm.sh/chart: {{ include "autoscan.chart" . }}
    app.kubernetes.io/name: {{ include "autoscan.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    {{- if .Chart.AppVersion }}
    app.kubernetes.io/version: {{ .Chart.AppVersion | quote }}
    {{- end }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    # Include extra labels defined globally in values.yaml
    {{- range $key, $value := .Values.extraLabels }}
    {{ $key }}: {{ $value | quote }}
    {{- end }}
type: Opaque
data:
  # Use the helper to render config.yml based on values
  config.yml: {{ include "autoscan.configYaml" . | b64enc }}
{{- end }}
