{{- /* Render Secret only if secrets.enabled is true and existingSecret is not provided */}}
{{- if and .Values.secrets.enabled (not .Values.secrets.existingSecret) -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "template.fullname" . }}-secrets # Or choose a different naming convention if preferred
  labels:
    {{- include "template.labels" . | nindent 4 }}
  {{- with (merge .Values.secrets.annotations .Values.commonAnnotations) }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
type: Opaque
data:
  {{- range $key, $value := .Values.secrets.data }}
  {{ $key }}: {{ $value | b64enc | quote }}
  {{- end }}
{{- end -}}
