{{- if not .Values.config.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "autopulse.config.secretName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "autopulse.labels" . | nindent 4 }}
    {{- range $key, $value := .Values.extraLabels }}
    {{ $key }}: {{ $value | quote }}
    {{- end }}
type: Opaque
data:
  {{ .Values.config.secretKey }}: {{ .Values.config.data | b64enc }}
{{- end }}
