{{- if not .Values.config.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "autopulse.config.secretName" . }}
  labels:
    {{- include "autopulse.labels" . | nindent 4 }}
type: Opaque
data:
  {{ .Values.config.secretKey }}: {{ .Values.config.data | b64enc }}
{{- end }}
