{{- if .Values.ui.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "autopulse.fullname" . }}-ui
  labels:
    {{- include "autopulse.labels" . | nindent 4 }}
    app.kubernetes.io/component: ui
spec:
  type: {{ .Values.ui.service.type }}
  ports:
    - port: {{ .Values.ui.service.port }}
      targetPort: http-ui
      protocol: TCP
      name: http-ui
  selector:
    {{- include "autopulse.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: ui
{{- end }}
