apiVersion: v1
kind: Service
metadata:
  name: {{ include "tautulli.fullname" . }}
  namespace: {{ .Values.namespace }}
  labels:
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/name: tautulli
    io.kompose.service: tautulli
    app: tautulli
    {{- include "tautulli.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
  - name: "{{ .Values.service.port }}"
    port: {{ .Values.service.port }}
    targetPort: 8181
  selector:
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/name: tautulli
    app: {{ include "tautulli.fullname" . }}
