# Values specific to the huntarr deployment, overriding defaults from the common chart.

common:
  # -- Global Settings Override --
  # fullnameOverride: "my-custom-huntarr-name" # Uncomment and set to override the full release name

  # Override workload settings from the common chart
  workloadType: deployment

  image:
    repository: huntarr/huntarr
    # pullPolicy: IfNotPresent # Inherited from common chart unless overridden
    tag: "latest"

  # Define the container port huntarr listens on
  containerPorts:
    - name: http
      containerPort: 9705
      protocol: TCP

  # Define the service to expose huntarr
  services:
    - name: huntarr
      enabled: true
      type: ClusterIP
      ports:
        - name: http
          port: 9705
          targetPort: http
          protocol: TCP
      # annotations: {}
      # labels: {}

  # Environment variables for huntarr
  env:
    TZ: "Europe/London"
    # Add other environment variables as needed

  # Persistence configuration for huntarr config
  persistence:
    enabled: true
    claims:
      - name: config
        mountPath: /config
        # existingClaim: "my-existing-huntarr-config-pvc" # Optional: Uncomment and set to use an existing PVC
        # --- PVC Spec (ignored if existingClaim is set) ---
        storageClassName: ""
        accessModes:
          - ReadWriteOnce
        size: 1Gi
        # annotations: {}
        # labels: {}

  # --- Other common chart values can be overridden below as needed ---
  # replicaCount: 1
  # resources: {}
  # ingress:
  #   enabled: false
  # ... etc.
