{{- /* Initialize flag for separator */ -}}
{{- $first := true -}}
{{- range $key, $value := .Values.persistence -}}
  {{- /* Check conditions to generate PVC */ -}}
  {{- if and $value.enabled (eq $value.type "pvc") (empty $value.existingClaim) -}}
    {{- /* Add separator before subsequent PVCs */ -}}
    {{- if $first -}}
      {{- $first = false -}}
    {{- else -}}
--- # Add separator
    {{- end -}}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ printf "%s-%s" (include "huntarr.fullname" $) $key }}
  namespace: {{ $.Release.Namespace }}
  labels:
    # Include standard labels defined in _helpers
    {{- include "huntarr.labels" $ | nindent 4 }}
    # Include extra labels defined globally in values.yaml
    {{- range $labelKey, $labelValue := $.Values.extraLabels }}
    {{ $labelKey }}: {{ $labelValue | quote }}
    {{- end }}
spec:
  accessModes:
    {{- toYaml $value.accessModes | nindent 4 }}
  {{- if $value.storageClass }}
  storageClassName: {{ $value.storageClass | quote }}
  {{- end }}
  resources:
    requests:
      storage: {{ $value.size | quote }}
  {{- end }} {{- /* End the 'if' block */ -}}
{{- end }} {{- /* End the 'range' loop */ -}}
