{{- if and (empty .Values.secretConfig.configSecretName) (empty .Values.secretConfig.secretName) }}
# This secret is only created if the user doesn't provide an existing secret
# via secretConfig.configSecretName or secretConfig.secretName in values.yaml.
# It provides the API_KEY value from secretConfig.apiKey.
apiVersion: v1
kind: Secret
metadata:
  # The name MUST match the secret name referenced in deployment.yaml
  name: {{ include "huntarr.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    # Include standard labels defined in _helpers
    {{- include "huntarr.labels" . | nindent 4 | trim }}
    # Include extra labels defined globally in values.yaml
    {{- range $key, $value := .Values.extraLabels }}
    {{ $key }}: {{ $value | quote }}
    {{- end }}
type: Opaque
data:
  # The key MUST match the key referenced in deployment.yaml (valueFrom.secretKeyRef.key)
  API_KEY: {{ .Values.secretConfig.apiKey | b64enc | quote }}
{{- end }}
