apiVersion: {{ include "appname.deployment.apiVersion" . }}
kind: Deployment
metadata:
  name: {{ include "appname.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "appname.labels" . | nindent 4 }}
    {{- range $key, $value := .Values.extraLabels }}
    {{ $key }}: {{ $value | quote }}
    {{- end }}
  {{- with .Values.deploymentAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "appname.selectorLabels" . | nindent 6 }}
  strategy:
    type: {{ .Values.strategy.type }}
    {{- if eq .Values.strategy.type "RollingUpdate" }}
    rollingUpdate:
      {{- toYaml .Values.strategy.rollingUpdate | nindent 6 }}
    {{- end }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "appname.selectorLabels" . | nindent 8 }}
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "appname.serviceAccountName" . }}
      {{- with .Values.podSecurityContext }}
      securityContext:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- if .Values.hostname }}
      hostname: {{ .Values.hostname | quote }}
      {{- end }}
      {{- if or .Values.initContainers .Values.cloudnativepg.enabled }}
      initContainers:
        {{- if .Values.cloudnativepg.enabled }}
        - name: config-init
          image: {{ .Values.cloudnativepg.initContainerImage }}
          imagePullPolicy: IfNotPresent
          resources:
            {{- toYaml .Values.cloudnativepg.resources | nindent 12 }}
          command:
            - "/bin/sh"
            - "-c"
            - |
              set -e
              
              # Determine the CloudnativePG secret name
              CNPG_SECRET_NAME="{{ .Values.cloudnativepg.secretName }}"
              if [ -z "$CNPG_SECRET_NAME" ]; then
                CNPG_SECRET_NAME="{{ .Values.cloudnativepg.clusterName }}-app"
              fi
              
              # Get CloudnativePG credentials from secret
              CNPG_NAMESPACE="{{ .Values.cloudnativepg.namespace | default .Release.Namespace }}"
              echo "Fetching CloudnativePG credentials from secret $CNPG_SECRET_NAME in namespace $CNPG_NAMESPACE"
              
              # Extract database connection details
              PG_HOST=$(kubectl get secret -n $CNPG_NAMESPACE $CNPG_SECRET_NAME -o jsonpath='{.data.host}' | base64 -d)
              PG_PORT=$(kubectl get secret -n $CNPG_NAMESPACE $CNPG_SECRET_NAME -o jsonpath='{.data.port}' | base64 -d)
              PG_USER=$(kubectl get secret -n $CNPG_NAMESPACE $CNPG_SECRET_NAME -o jsonpath='{.data.user}' | base64 -d)
              PG_PASSWORD=$(kubectl get secret -n $CNPG_NAMESPACE $CNPG_SECRET_NAME -o jsonpath='{.data.password}' | base64 -d)
              
              # Check if config.xml already exists
              CONFIG_FILE="/config/config.xml"
              TEMP_CONFIG="/config-init/config.xml"
              NEW_CONFIG="/config-init/new-config.xml"
              
              if [ -f "$CONFIG_FILE" ]; then
                echo "Existing config.xml found, updating only necessary fields"
                cp "$CONFIG_FILE" "$TEMP_CONFIG"
                
                # Function to update XML value
                update_xml_value() {
                  local tag=$1
                  local value=$2
                  local file=$3
                  
                  # Check if tag exists
                  if grep -q "<$tag>" "$file"; then
                    # Replace existing value
                    sed -i "s|<$tag>.*</$tag>|<$tag>$value</$tag>|g" "$file"
                  else
                    # Add new tag before closing Config tag
                    sed -i "s|</Config>|  <$tag>$value</$tag>\n</Config>|g" "$file"
                  fi
                }
                
                # Update PostgreSQL settings
                update_xml_value "PostgresUser" "$PG_USER" "$TEMP_CONFIG"
                update_xml_value "PostgresPassword" "$PG_PASSWORD" "$TEMP_CONFIG"
                update_xml_value "PostgresHost" "$PG_HOST" "$TEMP_CONFIG"
                update_xml_value "PostgresPort" "$PG_PORT" "$TEMP_CONFIG"
                update_xml_value "PostgresMainDb" "{{ .Values.cloudnativepg.mainDbName }}" "$TEMP_CONFIG"
                update_xml_value "PostgresLogDb" "{{ .Values.cloudnativepg.logDbName }}" "$TEMP_CONFIG"
                
                # Update other values from appConfig if they're set
                update_xml_value "BindAddress" "{{ .Values.appConfig.bindAddress }}" "$TEMP_CONFIG"
                update_xml_value "Port" "{{ .Values.appConfig.port }}" "$TEMP_CONFIG"
                update_xml_value "SslPort" "{{ .Values.appConfig.sslPort }}" "$TEMP_CONFIG"
                update_xml_value "EnableSsl" "{{ .Values.appConfig.enableSsl }}" "$TEMP_CONFIG"
                update_xml_value "LaunchBrowser" "{{ .Values.appConfig.launchBrowser }}" "$TEMP_CONFIG"
                update_xml_value "AuthenticationMethod" "{{ .Values.appConfig.authenticationMethod }}" "$TEMP_CONFIG"
                update_xml_value "AuthenticationRequired" "{{ .Values.appConfig.authenticationRequired }}" "$TEMP_CONFIG"
                update_xml_value "Branch" "{{ .Values.appConfig.branch }}" "$TEMP_CONFIG"
                update_xml_value "LogLevel" "{{ .Values.appConfig.logLevel }}" "$TEMP_CONFIG"
                update_xml_value "SslCertPath" "{{ .Values.appConfig.sslCertPath }}" "$TEMP_CONFIG"
                update_xml_value "InstanceName" "{{ .Values.appConfig.instanceName }}" "$TEMP_CONFIG"
                update_xml_value "UpdateMechanism" "{{ .Values.appConfig.updateMechanism }}" "$TEMP_CONFIG"
              else
                echo "No existing config.xml found, creating new one"
                # Create a new config.xml with default values and PostgreSQL settings
                cat > "$TEMP_CONFIG" << EOF
              <Config>
                <BindAddress>{{ .Values.appConfig.bindAddress }}</BindAddress>
                <Port>{{ .Values.appConfig.port }}</Port>
                <SslPort>{{ .Values.appConfig.sslPort }}</SslPort>
                <EnableSsl>{{ .Values.appConfig.enableSsl }}</EnableSsl>
                <LaunchBrowser>{{ .Values.appConfig.launchBrowser }}</LaunchBrowser>
                <ApiKey>{{ .Values.secretConfig.apiKey | default (randAlphaNum 32) }}</ApiKey>
                <AuthenticationMethod>{{ .Values.appConfig.authenticationMethod }}</AuthenticationMethod>
                <AuthenticationRequired>{{ .Values.appConfig.authenticationRequired }}</AuthenticationRequired>
                <Branch>{{ .Values.appConfig.branch }}</Branch>
                <LogLevel>{{ .Values.appConfig.logLevel }}</LogLevel>
                <SslCertPath>{{ .Values.appConfig.sslCertPath }}</SslCertPath>
                <SslCertPassword>{{ .Values.secretConfig.sslCertPassword | default "" }}</SslCertPassword>
                <UrlBase>{{ .Values.appConfig.urlBase }}</UrlBase>
                <InstanceName>{{ .Values.appConfig.instanceName }}</InstanceName>
                <UpdateMechanism>{{ .Values.appConfig.updateMechanism }}</UpdateMechanism>
                <PostgresUser>$PG_USER</PostgresUser>
                <PostgresPassword>$PG_PASSWORD</PostgresPassword>
                <PostgresHost>$PG_HOST</PostgresHost>
                <PostgresPort>$PG_PORT</PostgresPort>
                <PostgresMainDb>{{ .Values.cloudnativepg.mainDbName }}</PostgresMainDb>
                <PostgresLogDb>{{ .Values.cloudnativepg.logDbName }}</PostgresLogDb>
              </Config>
              EOF
              fi
              
              # If additional config secret is provided, merge it
              {{- if .Values.additionalConfig.enabled }}
              if [ -n "{{ .Values.additionalConfig.secretName }}" ] && [ -n "{{ .Values.additionalConfig.secretKey }}" ]; then
                echo "Merging additional configuration from secret {{ .Values.additionalConfig.secretName }}"
                ADDITIONAL_CONFIG=$(kubectl get secret -n {{ .Release.Namespace }} {{ .Values.additionalConfig.secretName }} -o jsonpath="{.data.{{ .Values.additionalConfig.secretKey }}}" | base64 -d)
                
                # Create a temporary file with the additional config
                echo "$ADDITIONAL_CONFIG" > /config-init/additional_config.xml
                
                # Use xmlstarlet or similar tool to merge configs if available
                # For now, just echo a message
                echo "Additional configuration will be applied"
              fi
              {{- end }}
              
              echo "Config file created successfully"
          volumeMounts:
            - name: config-init-volume
              mountPath: /config-init
            - name: config
              mountPath: /config
        {{- end }}
        {{- if .Values.initContainers }}
        {{- toYaml .Values.initContainers | nindent 8 }}
        {{- end }}
      {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          {{- with .Values.containerSecurityContext }}
          securityContext:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http # Matches service port name
              containerPort: {{ .Values.service.port }}
              protocol: TCP
          {{- with .Values.env }}
          env:
            {{- range $key, $value := . }}
            - name: {{ $key }}
              value: {{ $value | quote }}
            {{- end }}
          {{- end }}
          {{- with .Values.envFrom }}
          envFrom:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- if .Values.livenessProbe.enabled }}
          livenessProbe:
            {{- /* Use exec probe for sonarr API check */}}
            exec:
              command:
              - /usr/bin/env
              - bash
              - -c
              - {{ .Values.livenessProbe.command | quote }}
            initialDelaySeconds: {{ .Values.livenessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.livenessProbe.periodSeconds }}
            timeoutSeconds: {{ .Values.livenessProbe.timeoutSeconds | default 10 }}
            failureThreshold: {{ .Values.livenessProbe.failureThreshold | default 3 }}
            successThreshold: 1
          {{- end }}
          {{- if .Values.readinessProbe.enabled }}
          readinessProbe:
            {{- if eq .Values.readinessProbe.type "httpGet" }}
            httpGet:
              path: {{ .Values.readinessProbe.path }}
              port: {{ .Values.readinessProbe.port | default "http" }}
            {{- else if eq .Values.readinessProbe.type "tcpSocket" }}
            tcpSocket:
              port: {{ .Values.readinessProbe.port | default "http" }}
            {{- else if eq .Values.readinessProbe.type "exec" }}
            exec:
              command:
                {{- toYaml .Values.readinessProbe.command | nindent 16 }}
            {{- end }}
            initialDelaySeconds: {{ .Values.readinessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.readinessProbe.periodSeconds }}
            timeoutSeconds: {{ .Values.readinessProbe.timeoutSeconds }}
            failureThreshold: {{ .Values.readinessProbe.failureThreshold }}
            {{- if .Values.readinessProbe.successThreshold }}
            successThreshold: {{ .Values.readinessProbe.successThreshold }}
            {{- end }}
          {{- end }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            {{- /* Mount the config PVC */}}
            {{- range $key, $value := .Values.persistence }}
            {{- if and $value.enabled (eq $key "config") }}
            - name: {{ $key }}
              mountPath: {{ $value.mountPath }}
              {{- if $value.subPath }}
              subPath: {{ $value.subPath }}
              {{- end }}
            {{- end }}
            {{- end }}
            {{- /* Mount config.xml from CloudnativePG init container */}}
            {{- if .Values.cloudnativepg.enabled }}
            - name: config-init-volume
              mountPath: /config/config.xml
              subPath: config.xml
              readOnly: true
            {{- end }}
            {{- /* Mount config.xml from secret into the config volume mount */}}
            {{- if and .Values.secretConfig (not .Values.secretConfig.existingSecretName) (not .Values.cloudnativepg.enabled) }}
            - name: config # Mount to the same volume as the PVC
              mountPath: /config/config.xml # Mount directly as config.xml
              subPath: config.xml           # Use the key from the secret
              readOnly: false # Needs to be writable initially if Sonarr modifies it? Check Sonarr behavior.
            {{- end }}
            {{- /* Mount other persistence volumes (PVC or NFS) */}}
            {{- range $key, $value := .Values.persistence }}
            {{- if and $value.enabled (ne $key "config") }}
            - name: {{ $key }}
              mountPath: {{ $value.mountPath }}
              {{- if $value.subPath }}
              subPath: {{ $value.subPath }}
              {{- end }}
              {{- if $value.readOnly }}
              readOnly: {{ $value.readOnly }}
              {{- end }}
            {{- end }}
            {{- end }}
            {{- /* Mount config.xml from user-specified existing Secret */}}
            {{- if and .Values.configXmlFromSecret.enabled .Values.configXmlFromSecret.secretName }}
            - name: config-xml-secret-volume
              mountPath: {{ printf "%s/%s" .Values.persistence.config.mountPath .Values.configXmlFromSecret.fileName }}
              subPath: {{ .Values.configXmlFromSecret.secretKey }}
              readOnly: {{ .Values.configXmlFromSecret.readOnly }}
            {{- end }}
            {{- with .Values.extraVolumeMounts }}
            {{- tpl (toYaml .) $ | nindent 12 }}
            {{- end }}
      volumes:
        {{- /* Define persistence volumes (PVC or NFS) */}}
        {{- range $key, $value := .Values.persistence }}
        {{- if $value.enabled }}
        - name: {{ $key }}
          {{- if eq $value.type "pvc" }}
          persistentVolumeClaim:
            claimName: {{ $value.existingClaim | default (printf "%s-%s" (include "appname.fullname" $) $key) }}
          {{- else if eq $value.type "hostPath" }}
          hostPath:
            path: {{ $value.path }}
            type: {{ $value.hostPathType | default "DirectoryOrCreate" }}
          {{- else if eq $value.type "emptyDir" }}
          emptyDir:
          {{- if $value.medium }}
            medium: {{ $value.medium }}
          {{- end }}
          {{- if $value.sizeLimit }}
            sizeLimit: {{ $value.sizeLimit }}
          {{- end }}
          {{- else if eq $value.type "nfs" }}
          nfs:
            server: {{ $value.server }}
            path: {{ $value.path }}
            readOnly: {{ $value.readOnly | default false }}
          {{- else if eq $value.type "iscsi" }}
          iscsi:
            targetPortal: {{ $value.targetPortal }}
            iqn: {{ $value.iqn }}
            lun: {{ $value.lun }}
            fsType: {{ $value.fsType | default "ext4" }}
            readOnly: {{ $value.readOnly | default false }}
            {{- if $value.secretRef }}
            secretRef:
              name: {{ $value.secretRef }}
            {{- end }}
          {{- end }}
        {{- end }}
        {{- end }}
        {{- /* Define config.xml secret volume only if not using existingSecretName and not using CloudnativePG */}}
        {{- if and .Values.secretConfig (not .Values.secretConfig.existingSecretName) (not .Values.cloudnativepg.enabled) }}
        - name: config # Use the same name as the PVC volume for the mount
          secret:
            secretName: {{ printf "%s-config" (include "appname.fullname" .) }}
            items:
              - key: config.xml # Key defined in secret.yaml
                path: config.xml # Path within the secret volume mount
        {{- end }}
        {{- /* Define config-init-volume for CloudnativePG integration */}}
        {{- if .Values.cloudnativepg.enabled }}
        - name: config-init-volume
          emptyDir: {}
        {{- end }}
        {{- /* Define volume for config.xml from user-specified existing Secret */}}
        {{- if and .Values.configXmlFromSecret.enabled .Values.configXmlFromSecret.secretName }}
        - name: config-xml-secret-volume
          secret:
            secretName: {{ .Values.configXmlFromSecret.secretName }}
            items:
              - key: {{ .Values.configXmlFromSecret.secretKey }}
                path: {{ .Values.configXmlFromSecret.secretKey }} # This path is relative to the secret mount, subPath uses this.
        {{- end }}
        {{- with .Values.extraVolumes }}
          {{- tpl (toYaml .) $ | nindent 8 }}
        {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
