{{- if and .Values.secretConfig (empty .Values.secretConfig.existingSecretName) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ printf "%s-config" (include "appname.fullname" .) }}
  namespace: {{ .Release.Namespace }}
  labels:
    # Include standard labels defined in _helpers
{{ include "appname.labels" . | indent 4 }}
    # Include extra labels defined globally in values.yaml
{{- range $key, $value := .Values.extraLabels }}
    {{ $key }}: {{ $value | quote }}
{{- end }}
type: Opaque
data:
  # Use config.xml as the key, matching the subPath in deployment.yaml
  config.xml: {{ include "sonarr.configfile" . | b64enc }}
{{- end }}
