apiVersion: v2
name: template
description: A Helm chart template for Kubernetes applications
# A chart can be either an 'application' or a 'library' chart.
# Application charts are installable charts. Library charts provide useful utilities
# or functions for the chart developer. They're included as a dependency of application charts.
type: application # Or 'library'

# This is the chart version. This version number should be incremented each time you make changes
# to the chart and its templates, including the app version.
# Versions are expected to follow Semantic Versioning (https://semver.org/)
version: 0.1.0

# This is the version number of the application being deployed. This version number should be
# incremented each time you make changes to the application. Versions are not expected to
# follow Semantic Versioning. They should reflect the version the application is using.
# It is recommended to use it with quotes.
appVersion: "1.0.0"

# Keywords to help users find your chart
keywords:
- template
- example

# Home page URL for your chart
home: https://example.com/helm-charts/template

# Source code URL for your chart
sources:
- https://github.com/example/helm-charts/tree/main/charts/template

# A list of maintainers for your chart
maintainers:
- name: Your Name
  email: your.email@example.com
  url: https://your.website.com

# Chart dependencies (optional)
# dependencies:
#   - name: common
#     version: "1.x.x"
#     repository: "https://charts.example.com/"
#     condition: common.enabled # Enable/disable the dependency based on a value

# Annotations are additional metadata for your chart (optional)
annotations:
  artifacthub.io/changes: |
    - kind: added
      description: Initial chart template creation.
  # Add other relevant annotations
