# ------------------------------------------------------------------------------
# Name and fullname override
# ------------------------------------------------------------------------------
# nameOverride: ""
# fullnameOverride: ""

# ------------------------------------------------------------------------------
# Namespace
# ------------------------------------------------------------------------------
namespace: default

# ------------------------------------------------------------------------------
# Image configuration
# ------------------------------------------------------------------------------
image:
  repository: cloudb0x/autoscan
  tag: latest
  pullPolicy: IfNotPresent

# ------------------------------------------------------------------------------
# Labels you want to add to your resources
# ------------------------------------------------------------------------------
labels: {}

# ------------------------------------------------------------------------------
# Replicas
# ------------------------------------------------------------------------------
replicaCount: 1

# ------------------------------------------------------------------------------
# Resource requests & limits
# ------------------------------------------------------------------------------
resources:
  limits:
    cpu: 50m
    memory: 128Mi
  requests:
    cpu: 10m
    memory: 64Mi

# ------------------------------------------------------------------------------
# Node scheduling
# ------------------------------------------------------------------------------
nodeSelector: {}
tolerations: []
affinity: {}

# ------------------------------------------------------------------------------
# Config section
# ------------------------------------------------------------------------------
config:
  # If non-empty, the chart will skip creating a new config secret
  # and reference the specified existing secret name for config.yml.
  existingSecret: ""

  # The "template-driven" config parameters.
  minimumAge: "5m"
  scanDelay: "30s"
  port: 3030

  triggers:
    lidarr:
      enabled: true
      priority: 1
    radarr:
      enabled: true
      priority: 2
    sonarr:
      enabled: true
      priority: 2

  targets:
    plex:
      url: ""
      token: "" # Used if useTokenSecret is false
      useTokenSecret: false # If true, we’ll do a placeholder in config.yml
      tokenSecret:
        name: "my-plex-token-secret"
        key: "token"

# ------------------------------------------------------------------------------
# Persistence
# ------------------------------------------------------------------------------
persistence:
  conf:
    enabled: true
    size: 500Mi
    existingClaim: ""
    storageClass: ""
  database:
    enabled: true
    size: 500Mi
    existingClaim: ""
    storageClass: ""

# ------------------------------------------------------------------------------
# Service configuration
# ------------------------------------------------------------------------------
service:
  type: ClusterIP
  port: 3030
