{{- if eq .Values.configXml.existingSecret "" }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "prowlarr.fullname" . }}-xml
  labels:
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/name: prowlarr
    {{- include "prowlarr.labels" . | nindent 4 }}
type: Opaque
data:
  config.xml: {{ include "prowlarr.configXml" . | b64enc }}
{{- end }}
