apiVersion: {{ include "prowlarr.deployment.apiVersion" . }}
kind: Deployment
metadata:
  name: {{ include "prowlarr.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "prowlarr.labels" . | nindent 4 }}
  {{- with .Values.deploymentAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "prowlarr.selectorLabels" . | nindent 6 }}
  strategy:
    type: {{ .Values.strategy.type }}
    {{- if eq .Values.strategy.type "RollingUpdate" }}
    rollingUpdate:
      {{- toYaml .Values.strategy.rollingUpdate | nindent 6 }}
    {{- end }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "prowlarr.selectorLabels" . | nindent 8 }}
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
        {{- with .Values.extraLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "prowlarr.serviceAccountName" . }}
      {{- with .Values.podSecurityContext }}
      securityContext:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- if .Values.cloudnativepg.enabled }}
      initContainers:
        - name: config-init
          image: {{ .Values.cloudnativepg.initContainer.image }}
          imagePullPolicy: {{ .Values.cloudnativepg.initContainer.imagePullPolicy }}
          resources:
            {{- toYaml .Values.cloudnativepg.initContainer.resources | nindent 12 }}
          command:
            - "/bin/sh"
            - "-c"
            - |
              set -e
              
              # Determine the CloudnativePG secret name
              CNPG_SECRET_NAME="{{ .Values.cloudnativepg.secretName }}"
              if [ -z "$CNPG_SECRET_NAME" ]; then
                CNPG_SECRET_NAME="{{ .Values.cloudnativepg.clusterName }}-app"
              fi
              
              # Get CloudnativePG credentials from secret
              CNPG_NAMESPACE="{{ .Values.cloudnativepg.namespace | default .Release.Namespace }}"
              echo "Fetching CloudnativePG credentials from secret $CNPG_SECRET_NAME in namespace $CNPG_NAMESPACE"
              
              # Extract database connection details
              PG_HOST=$(kubectl get secret -n $CNPG_NAMESPACE $CNPG_SECRET_NAME -o jsonpath='{.data.host}' | base64 -d)
              PG_PORT=$(kubectl get secret -n $CNPG_NAMESPACE $CNPG_SECRET_NAME -o jsonpath='{.data.port}' | base64 -d)
              PG_USER=$(kubectl get secret -n $CNPG_NAMESPACE $CNPG_SECRET_NAME -o jsonpath='{.data.user}' | base64 -d)
              PG_PASSWORD=$(kubectl get secret -n $CNPG_NAMESPACE $CNPG_SECRET_NAME -o jsonpath='{.data.password}' | base64 -d)
              
              # Get API key from secret or values
              {{- if .Values.secretConfig.apiKeySecretRef }}
              API_KEY_SECRET_NAME="{{ .Values.secretConfig.apiKeySecretRef.name }}"
              API_KEY_SECRET_KEY="{{ .Values.secretConfig.apiKeySecretRef.key }}"
              if [ -n "$API_KEY_SECRET_NAME" ] && [ -n "$API_KEY_SECRET_KEY" ]; then
                echo "Fetching API key from secret $API_KEY_SECRET_NAME in namespace {{ .Release.Namespace }}"
                API_KEY=$(kubectl get secret -n {{ .Release.Namespace }} $API_KEY_SECRET_NAME -o jsonpath="{.data.$API_KEY_SECRET_KEY}" | base64 -d)
                if [ -z "$API_KEY" ]; then
                  echo "Error: API key not found in secret $API_KEY_SECRET_NAME with key $API_KEY_SECRET_KEY"
                  exit 1
                fi
              else
                echo "Error: API key secret reference is incomplete. Both name and key must be provided"
                exit 1
              fi
              {{- else if .Values.secretConfig.apiKey }}
              API_KEY="{{ .Values.secretConfig.apiKey }}"
              {{- else }}
              echo "Error: API key is required. Please provide it either in values.yaml (secretConfig.apiKey) or as a secret reference (secretConfig.apiKeySecretRef)"
              exit 1
              {{- end }}
              
              # Check if config.xml already exists
              CONFIG_FILE="/config/config.xml"
              TEMP_CONFIG="/config-init/config.xml"
              NEW_CONFIG="/config-init/new-config.xml"
              
              if [ -f "$CONFIG_FILE" ]; then
                echo "Existing config.xml found, updating only necessary fields"
                cp "$CONFIG_FILE" "$TEMP_CONFIG"
                
                # Function to update XML value
                update_xml_value() {
                  local tag=$1
                  local value=$2
                  local file=$3
                  
                  # Check if tag exists
                  if grep -q "<$tag>" "$file"; then
                    # Replace existing value
                    sed -i "s|<$tag>.*</$tag>|<$tag>$value</$tag>|g" "$file"
                  else
                    # Add new tag before closing Config tag
                    sed -i "s|</Config>|  <$tag>$value</$tag>\n</Config>|g" "$file"
                  fi
                }
                
                # Update PostgreSQL settings
                update_xml_value "PostgresUser" "$PG_USER" "$TEMP_CONFIG"
                update_xml_value "PostgresPassword" "$PG_PASSWORD" "$TEMP_CONFIG"
                update_xml_value "PostgresHost" "$PG_HOST" "$TEMP_CONFIG"
                update_xml_value "PostgresPort" "$PG_PORT" "$TEMP_CONFIG"
                update_xml_value "PostgresMainDb" "{{ .Values.cloudnativepg.mainDb }}" "$TEMP_CONFIG"
                update_xml_value "PostgresLogDb" "{{ .Values.cloudnativepg.logDb }}" "$TEMP_CONFIG"
                
                # Update other values from secretConfig if they're set
                {{- if .Values.secretConfig.bindAddress }}
                update_xml_value "BindAddress" "{{ .Values.secretConfig.bindAddress }}" "$TEMP_CONFIG"
                {{- end }}
                {{- if .Values.secretConfig.port }}
                update_xml_value "Port" "{{ .Values.secretConfig.port }}" "$TEMP_CONFIG"
                {{- end }}
                {{- if .Values.secretConfig.sslPort }}
                update_xml_value "SslPort" "{{ .Values.secretConfig.sslPort }}" "$TEMP_CONFIG"
                {{- end }}
                {{- if .Values.secretConfig.enableSsl }}
                update_xml_value "EnableSsl" "{{ .Values.secretConfig.enableSsl }}" "$TEMP_CONFIG"
                {{- end }}
                {{- if .Values.secretConfig.launchBrowser }}
                update_xml_value "LaunchBrowser" "{{ .Values.secretConfig.launchBrowser }}" "$TEMP_CONFIG"
                {{- end }}
                # Update API key with value fetched from secret
                update_xml_value "ApiKey" "$API_KEY" "$TEMP_CONFIG"
                {{- if .Values.secretConfig.authenticationMethod }}
                update_xml_value "AuthenticationMethod" "{{ .Values.secretConfig.authenticationMethod }}" "$TEMP_CONFIG"
                {{- end }}
                {{- if .Values.secretConfig.authenticationRequired }}
                update_xml_value "AuthenticationRequired" "{{ .Values.secretConfig.authenticationRequired }}" "$TEMP_CONFIG"
                {{- end }}
                {{- if .Values.secretConfig.branch }}
                update_xml_value "Branch" "{{ .Values.secretConfig.branch }}" "$TEMP_CONFIG"
                {{- end }}
                {{- if .Values.secretConfig.logLevel }}
                update_xml_value "LogLevel" "{{ .Values.secretConfig.logLevel }}" "$TEMP_CONFIG"
                {{- end }}
                {{- if .Values.secretConfig.sslCertPath }}
                update_xml_value "SslCertPath" "{{ .Values.secretConfig.sslCertPath }}" "$TEMP_CONFIG"
                {{- end }}
                {{- if or .Values.secretConfig.sslCertPassword .Values.secretConfig.sslCertPasswordSecretRef }}
                update_xml_value "SslCertPassword" "{{ default .Values.secretConfig.sslCertPassword (include "prowlarr.secretValue" (dict "secretRef" .Values.secretConfig.sslCertPasswordSecretRef "context" $)) }}" "$TEMP_CONFIG"
                {{- end }}
                {{- if .Values.secretConfig.urlBase }}
                update_xml_value "UrlBase" "{{ .Values.secretConfig.urlBase }}" "$TEMP_CONFIG"
                {{- end }}
                {{- if .Values.secretConfig.instanceName }}
                update_xml_value "InstanceName" "{{ .Values.secretConfig.instanceName }}" "$TEMP_CONFIG"
                {{- end }}
                {{- if .Values.secretConfig.updateMechanism }}
                update_xml_value "UpdateMechanism" "{{ .Values.secretConfig.updateMechanism }}" "$TEMP_CONFIG"
                {{- end }}
              else
                echo "No existing config.xml found, creating new one"
                # Create a new config.xml with default values and PostgreSQL settings
                cat > "$TEMP_CONFIG" << EOF
              <Config>
                <BindAddress>{{ .Values.secretConfig.bindAddress }}</BindAddress>
                <Port>{{ .Values.secretConfig.port }}</Port>
                <SslPort>{{ .Values.secretConfig.sslPort }}</SslPort>
                <EnableSsl>{{ .Values.secretConfig.enableSsl }}</EnableSsl>
                <LaunchBrowser>{{ .Values.secretConfig.launchBrowser }}</LaunchBrowser>
                <ApiKey>$API_KEY</ApiKey>
                <AuthenticationMethod>{{ .Values.secretConfig.authenticationMethod }}</AuthenticationMethod>
                <AuthenticationRequired>{{ .Values.secretConfig.authenticationRequired }}</AuthenticationRequired>
                <Branch>{{ .Values.secretConfig.branch }}</Branch>
                <LogLevel>{{ .Values.secretConfig.logLevel }}</LogLevel>
                <SslCertPath>{{ .Values.secretConfig.sslCertPath }}</SslCertPath>
                <SslCertPassword>{{ default .Values.secretConfig.sslCertPassword (include "prowlarr.secretValue" (dict "secretRef" .Values.secretConfig.sslCertPasswordSecretRef "context" $)) }}</SslCertPassword>
                <UrlBase>{{ .Values.secretConfig.urlBase }}</UrlBase>
                <InstanceName>{{ .Values.secretConfig.instanceName }}</InstanceName>
                <UpdateMechanism>{{ .Values.secretConfig.updateMechanism }}</UpdateMechanism>
                <PostgresUser>$PG_USER</PostgresUser>
                <PostgresPassword>$PG_PASSWORD</PostgresPassword>
                <PostgresHost>$PG_HOST</PostgresHost>
                <PostgresPort>$PG_PORT</PostgresPort>
                <PostgresMainDb>{{ .Values.cloudnativepg.mainDb }}</PostgresMainDb>
                <PostgresLogDb>{{ .Values.cloudnativepg.logDb }}</PostgresLogDb>
              </Config>
              EOF
              fi
              
              # If additional config secret is provided, merge it
              if [ -n "{{ .Values.additionalConfig.secretRef.name }}" ] && [ -n "{{ .Values.additionalConfig.secretRef.key }}" ]; then
                echo "Merging additional configuration from secret {{ .Values.additionalConfig.secretRef.name }}"
                ADDITIONAL_CONFIG=$(kubectl get secret -n {{ .Release.Namespace }} {{ .Values.additionalConfig.secretRef.name }} -o jsonpath="{.data.{{ .Values.additionalConfig.secretRef.key }}}" | base64 -d)
                
                # Create a temporary file with the additional config
                echo "$ADDITIONAL_CONFIG" > /config-init/additional_config.xml
                
                # Use xmlstarlet or similar tool to merge configs if available
                # For now, just echo a message
                echo "Additional configuration will be applied"
              fi
              
              echo "Config file created successfully"
          volumeMounts:
            - name: config-init-volume
              mountPath: /config-init
            {{- range $key, $value := .Values.persistence }}
            {{- if and $value.enabled (eq $key "config") }}
            - name: {{ $key }}
              mountPath: /config
              {{- if $value.subPath }}
              subPath: {{ $value.subPath }}
              {{- end }}
            {{- end }}
            {{- end }}
      {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          {{- with .Values.containerSecurityContext }}
          securityContext:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http # Matches service port name
              containerPort: {{ .Values.service.port }}
              protocol: TCP
          {{- if .Values.env }}
          env:
            {{- range $key, $value := .Values.env }}
            - name: {{ $key }}
              value: {{ $value | quote }}
            {{- end }}
          {{- end }}
          {{- with .Values.envFrom }}
          envFrom:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- if .Values.livenessProbe.enabled }}
          livenessProbe:
            {{- if eq .Values.livenessProbe.type "httpGet" }}
            httpGet:
              path: {{ .Values.livenessProbe.path }}
              port: http # Matches port name
            {{- else if eq .Values.livenessProbe.type "tcpSocket" }}
            tcpSocket:
              port: http # Matches port name
            {{- else if eq .Values.livenessProbe.type "exec" }}
            exec:
              command:
                {{- toYaml .Values.livenessProbe.command | nindent 16 }}
            {{- end }}
            initialDelaySeconds: {{ .Values.livenessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.livenessProbe.periodSeconds }}
            timeoutSeconds: {{ .Values.livenessProbe.timeoutSeconds }}
            failureThreshold: {{ .Values.livenessProbe.failureThreshold }}
          {{- end }}
          {{- if .Values.readinessProbe.enabled }}
          readinessProbe:
            {{- if eq .Values.readinessProbe.type "httpGet" }}
            httpGet:
              path: {{ .Values.readinessProbe.path }}
              port: http # Matches port name
            {{- else if eq .Values.readinessProbe.type "tcpSocket" }}
            tcpSocket:
              port: http # Matches port name
            {{- else if eq .Values.readinessProbe.type "exec" }}
            exec:
              command:
                {{- toYaml .Values.readinessProbe.command | nindent 16 }}
            {{- end }}
            initialDelaySeconds: {{ .Values.readinessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.readinessProbe.periodSeconds }}
            timeoutSeconds: {{ .Values.readinessProbe.timeoutSeconds }}
            failureThreshold: {{ .Values.readinessProbe.failureThreshold }}
          {{- end }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            {{- if .Values.secretConfig.existingSecretName }}
            # Mount the config.xml from an existing secret
            - name: config-file-secret
              mountPath: /config/config.xml # Prowlarr expects config.xml here
              subPath: {{ .Values.secretConfig.existingSecretKey | default "config.xml" }} # Key in the existing secret
              readOnly: true # Config is managed via secret, should be read-only in pod
            {{- else if .Values.cloudnativepg.enabled }}
            # Mount the config.xml from the init container
            - name: config-init-volume
              mountPath: /config/config.xml # Prowlarr expects config.xml here
              subPath: config.xml           # Matches file created in init container
              readOnly: true # Config is managed via init container, should be read-only in pod
            {{- else }}
            # Mount the config.xml from the chart-managed secret
            - name: config-file-secret
              mountPath: /config/config.xml # Prowlarr expects config.xml here
              subPath: config.xml           # Matches key in secret.yaml
              readOnly: true # Config is managed via secret, should be read-only in pod
            {{- end }}
            {{- range $key, $value := .Values.persistence }}
            {{- if $value.enabled }}
            - name: {{ $key }}
              mountPath: {{ $value.mountPath }}
              {{- if $value.subPath }}
              subPath: {{ $value.subPath }}
              {{- end }}
              {{- if $value.readOnly }}
              readOnly: {{ $value.readOnly }}
              {{- end }}
            {{- end }}
            {{- end }}
      volumes:
        # Define the volume for the config secret (either existing or chart-managed)
        - name: config-file-secret
          {{- if .Values.cloudnativepg.enabled }}
          emptyDir: {}
          {{- else if .Values.secretConfig.existingSecretName }}
          secret:
            secretName: {{ .Values.secretConfig.existingSecretName }}
            items:
              - key: {{ .Values.secretConfig.existingSecretKey | default "config.xml" }}
                path: {{ .Values.secretConfig.existingSecretKey | default "config.xml" }}
          {{- else }}
          secret:
            secretName: {{ printf "%s-config" (include "prowlarr.fullname" .) }}
            items:
              # Ensure this key matches the key in secret.yaml and volumeMounts.subPath
              - key: config.xml
                path: config.xml
          {{- end }}
        {{- if .Values.cloudnativepg.enabled }}
        - name: config-init-volume
          emptyDir: {}
        {{- end }}
        {{- range $key, $value := .Values.persistence }}
        {{- if $value.enabled }}
        - name: {{ $key }}
          {{- if eq $value.type "pvc" }}
          persistentVolumeClaim:
            claimName: {{ $value.existingClaim | default (printf "%s-%s" (include "prowlarr.fullname" $) $key) }}
          {{- else if eq $value.type "hostPath" }}
          hostPath:
            path: {{ $value.path }}
            type: {{ $value.hostPathType | default "DirectoryOrCreate" }}
          {{- else if eq $value.type "emptyDir" }}
          emptyDir:
          {{- if $value.medium }}
            medium: {{ $value.medium }}
          {{- end }}
          {{- if $value.sizeLimit }}
            sizeLimit: {{ $value.sizeLimit }}
          {{- end }}
          {{- else if eq $value.type "nfs" }}
          nfs:
            server: {{ $value.server }}
            path: {{ $value.path }}
            readOnly: {{ $value.readOnly | default false }}
          {{- else if eq $value.type "iscsi" }}
          iscsi:
            targetPortal: {{ $value.targetPortal }}
            iqn: {{ $value.iqn }}
            lun: {{ $value.lun }}
            fsType: {{ $value.fsType | default "ext4" }}
            readOnly: {{ $value.readOnly | default false }}
            {{- if $value.secretRef }}
            secretRef:
              name: {{ $value.secretRef }}
            {{- end }}
          {{- end }}
        {{- end }}
        {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
