apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "prowlarr.fullname" . }}
  namespace: {{ .Values.namespace }}
  labels:
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/name: prowlarr
    {{- include "prowlarr.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/instance: {{ .Release.Name }}
      app.kubernetes.io/name: prowlarr
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app.kubernetes.io/instance: {{ .Release.Name }}
        app.kubernetes.io/name: prowlarr
        {{- include "prowlarr.labels" . | nindent 8 }}
    spec:
      hostname: {{ .Values.hostname | quote }}
      nodeSelector:
        {{- toYaml .Values.nodeSelector | nindent 8 }}
      tolerations:
        {{- toYaml .Values.tolerations | nindent 8 }}
      affinity:
        {{- toYaml .Values.affinity | nindent 8 }}

      containers:
      - name: prowlarr
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        env:
        - name: UMASK
          value: {{ .Values.env.UMASK | quote }}
        ports:
        - containerPort: 9696
          protocol: TCP
        resources:
          limits:
            memory: {{ .Values.resources.limits.memory }}
          requests:
            cpu: {{ .Values.resources.requests.cpu }}
            memory: {{ .Values.resources.requests.memory }}
        {{- if .Values.livenessProbe.enabled }}
        livenessProbe:
          exec:
            command:
            - /usr/bin/env
            - bash
            - -c
            - {{ .Values.livenessProbe.command | quote }}
          initialDelaySeconds: {{ .Values.livenessProbe.initialDelaySeconds }}
          periodSeconds: {{ .Values.livenessProbe.periodSeconds }}
        {{- end }}
        volumeMounts:
        - name: prowlarr-config
          mountPath: /config
        - name: prowlarr-xml
          mountPath: /tmp/config-xml
          readOnly: true
        lifecycle:
          postStart:
            exec:
              command:
              - /bin/sh
              - -c
              - |
                # Copy our generated or existing config.xml from secret to /config
                cp /tmp/config-xml/config.xml /config/config.xml

      volumes:
      - name: prowlarr-config
        persistentVolumeClaim:
          claimName:{{- if .Values.persistence.config.existingClaim }} {{ .Values.persistence.config.existingClaim }}{{- else }} {{ include "prowlarr.fullname" . }}-config{{- end }}

      - name: prowlarr-xml
        secret:
          secretName:{{- if .Values.configXml.existingSecret }} {{ .Values.configXml.existingSecret }}{{- else }} {{ include "prowlarr.fullname" . }}-xml{{- end }}

      restartPolicy: Always
