{{- if and (empty .Values.secretConfig.existingSecretName) (not .Values.cloudnativepg.enabled) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ printf "%s-config" (include "prowlarr.fullname" .) }}
  namespace: {{ .Release.Namespace }}
  labels:
    # Include standard labels defined in _helpers
{{ include "prowlarr.labels" . | indent 4 }}
    # Include extra labels defined globally in values.yaml
{{- range $key, $value := .Values.extraLabels }}
    {{ $key }}: {{ $value | quote }}
{{- end }}
type: Opaque
data:
  # config.xml is expected by Prowlarr and mounted in deployment.yaml
  config.xml: |-
    {{ include "prowlarr.configXml" . | b64enc }}
{{- end }}
