{{- /* Create PVC only if .Values.persistence.config is enabled, type is pvc, and existingClaim is empty */}}
{{- if and .Values.persistence.config.enabled (eq .Values.persistence.config.type "pvc") (empty .Values.persistence.config.existingClaim) }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "overseerr.fullname" . }}-config
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/name: {{ include "overseerr.name" . }}
{{ include "overseerr.labels" . | nindent 4 }}
spec:
  accessModes:
{{ toYaml .Values.persistence.config.accessModes | nindent 4 }}
  {{- if .Values.persistence.config.storageClass }}
  storageClassName: {{ .Values.persistence.config.storageClass | quote }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.persistence.config.size | quote }}
{{- end }}
