{{- if empty .Values.secretConfig.existingSecretName }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ printf "%s-config" (include "overseerr.fullname" .) }} # Use overseerr helper
  namespace: {{ .Release.Namespace }}
  labels:
    # Include standard labels defined in _helpers
{{ include "overseerr.labels" . | indent 4 }} # Use overseerr helper
    # Include extra labels defined globally in values.yaml
{{- range $key, $value := .Values.extraLabels }}
    {{ $key }}: {{ $value | quote }}
{{- end }}
type: Opaque
# data: {} # Removing data section as Overseerr config is typically not managed this way
{{- end }}
