apiVersion: v1
kind: Service
metadata:
  name: {{ include "overseerr.fullname" . }}
  namespace: {{ .Values.namespace }}
  labels:
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/name: overseerr
    io.kompose.service: overseerr
    app: overseerr
    {{- include "overseerr.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: "{{ .Values.service.port }}"
    port: {{ .Values.service.port }}
    targetPort: 5055
  selector:
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/name: overseerr
    app: {{ include "overseerr.fullname" . }}
