apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "autoscan.fullname" . }}
  labels:
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/name: autoscan
    {{- include "autoscan.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/instance: {{ .Release.Name }}
      app.kubernetes.io/name: autoscan
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app.kubernetes.io/instance: {{ .Release.Name }}
        app.kubernetes.io/name: autoscan
        {{- include "autoscan.labels" . | nindent 8 }}
    spec:
      nodeSelector: {{- toYaml .Values.nodeSelector | nindent 6 }}
      tolerations: {{- toYaml .Values.tolerations | nindent 6 }}
      affinity: {{- toYaml .Values.affinity | nindent 6 }}
      containers:
        - name: autoscan
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 3030
              protocol: TCP
          resources:
            limits:
              cpu: {{ .Values.resources.limits.cpu }}
              memory: {{ .Values.resources.limits.memory }}
            requests:
              cpu: {{ .Values.resources.requests.cpu }}
              memory: {{ .Values.resources.requests.memory }}
          lifecycle:
            postStart:
              exec:
                command: ["/bin/sh", "-c", "cat /tmp/config/config.yml > /config/config.yml"]
          volumeMounts:
            - name: autoscan-config
              mountPath: /tmp/config
            - name: autoscan-conf
              mountPath: /config
            - name: autoscan-database
              mountPath: /data
      restartPolicy: Always
      volumes:
        - name: autoscan-config
          secret:
            secretName: {{ .Values.autoscanConfigSecretName }}
        - name: autoscan-conf
          persistentVolumeClaim:
            claimName: {{- if .Values.persistence.conf.existingClaim -}}
              {{ .Values.persistence.conf.existingClaim }}
            {{- else -}}
              {{ include "autoscan.fullname" . }}-conf
            {{- end }}
        - name: autoscan-database
          persistentVolumeClaim:
            claimName: {{- if .Values.persistence.database.existingClaim -}}
              {{ .Values.persistence.database.existingClaim }}
            {{- else -}}
              {{ include "autoscan.fullname" . }}-database
            {{- end }}
