{{- if eq .Values.config.existingSecret "" }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "autoscan.fullname" . }}-config
  labels:
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/name: autoscan
    {{- include "autoscan.labels" . | nindent 4 }}
type: Opaque
data:
  config.yml: {{ include "autoscan.configYaml" . | b64enc }}
{{- end }}
