# Default values for appname.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

# -- Override the name of the chart.
nameOverride: ""
# -- Override the full name of the chart.
fullnameOverride: ""

# -- Number of replicas for the deployment.
replicaCount: 1

image:
  # -- Container image repository. Placeholder: Replace with actual repository.
  repository: nginx # Example placeholder
  # -- Container image pull policy.
  pullPolicy: IfNotPresent
  # -- Container image tag. Defaults to .Chart.AppVersion. Placeholder: Replace if needed.
  tag: ""

# -- Optional list of image pull secrets.
imagePullSecrets: []
# -- Optional extra labels to add to all resources.
extraLabels: {}

# -- Deployment strategy.
strategy:
  type: RollingUpdate
  rollingUpdate:
    maxSurge: "25%"
    maxUnavailable: "25%"

serviceAccount:
  # -- Specifies whether a service account should be created.
  create: true
  # -- The name of the service account to use. If not set and create is true, a name is generated using the fullname template.
  name: ""
  # -- Annotations to add to the service account.
  annotations: {}

# -- Annotations to add to the pod.
podAnnotations: {}
# -- Labels to add to the pod.
podLabels: {}
# -- Annotations to add to the deployment.
deploymentAnnotations: {}

# -- Security context for the pod.
# See https://kubernetes.io/docs/tasks/configure-pod-container/security-context/
podSecurityContext: {}
  # fsGroup: 1000
  # runAsUser: 1000
  # runAsGroup: 1000
  # runAsNonRoot: true

# -- Security context for the container.
# See https://kubernetes.io/docs/tasks/configure-pod-container/security-context/
containerSecurityContext: {}
  # allowPrivilegeEscalation: false
  # capabilities:
  #   drop:
  #     - ALL
  # readOnlyRootFilesystem: true
  # runAsUser: 1000
  # runAsGroup: 1000
  # runAsNonRoot: true

service:
  # -- Kubernetes service type.
  type: ClusterIP
  # -- Service port. Placeholder: Replace with application's port.
  port: 80
  # -- Service target port. Defaults to the service port. Placeholder: Replace if different.
  targetPort: 80
  # -- Node port (only used if type is NodePort).
  nodePort: null
  # -- Annotations for the service.
  annotations: {}
  # -- Labels for the service.
  labels: {}

ingress:
  # -- Enable ingress controller resource.
  enabled: false
  # -- Ingress class name.
  className: ""
  # -- Annotations for the ingress.
  annotations: {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  # -- Ingress host configuration. Placeholder: Replace host.
  hosts:
  - host: appname.local
    paths:
    - path: /
      pathType: ImplementationSpecific
  # -- Ingress TLS configuration.
  tls: []
  #  - secretName: appname-tls
  #    hosts:
  #      - appname.local

  # -- Resource requests and limits.
  # See https://kubernetes.io/docs/concepts/configuration/manage-resources-containers/
resources: {}
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

# -- Liveness probe configuration.
# See https://kubernetes.io/docs/tasks/configure-pod-container/configure-liveness-readiness-startup-probes/
livenessProbe:
  enabled: true
  type: httpGet # Options: httpGet, tcpSocket, exec. Placeholder: Adjust type/path/port.
  path: / # Placeholder: Adjust path.
  port: http # References service.port name
  initialDelaySeconds: 30
  periodSeconds: 30
  timeoutSeconds: 5
  failureThreshold: 3
  # For exec type:
  # command:
  #   - cat
  #   - /tmp/healthy

  # -- Readiness probe configuration.
  # See https://kubernetes.io/docs/tasks/configure-pod-container/configure-liveness-readiness-startup-probes/
readinessProbe:
  enabled: true
  type: httpGet # Options: httpGet, tcpSocket, exec. Placeholder: Adjust type/path/port.
  path: / # Placeholder: Adjust path.
  port: http # References service.port name
  initialDelaySeconds: 15
  periodSeconds: 15
  timeoutSeconds: 5
  failureThreshold: 3
  # For exec type:
  # command:
  #   - cat
  #   - /tmp/ready

  # -- Persistence configuration. Defines volumes and mounts.
  # See https://kubernetes.io/docs/concepts/storage/persistent-volumes/
  # Placeholder: Adjust persistence keys (e.g., 'config', 'data') and settings as needed.
persistence:
  config:
    # -- Enable persistence for config volume.
    enabled: true
    # -- Type of volume. Options: pvc, hostPath, emptyDir, nfs, iscsi.
    type: pvc
    # -- Mount path inside the container. Placeholder: Adjust mount path.
    mountPath: /config
    # -- SubPath within the volume to mount.
    # subPath: ""
    # -- Mount read-only.
    # readOnly: false

    # -- PVC specific settings (ignored if type is not pvc)
    # -- Access modes for the PVC.
    accessModes:
    - ReadWriteOnce
    # -- Size of the PVC.
    size: 1Gi
    # -- Storage class for the PVC. If "", uses default.
    storageClass: ""
    # -- Use an existing PVC instead of creating one.
    existingClaim: ""
    # -- hostPath specific settings (ignored if type is not hostPath)
    # path: /path/on/host
    # hostPathType: DirectoryOrCreate

    # -- emptyDir specific settings (ignored if type is not emptyDir)
    # medium: "" # Memory or ""
    # sizeLimit: ""

    # -- NFS specific settings (ignored if type is not nfs)
    # server: nfs.example.com
    # path: /exported/path

    # -- iSCSI specific settings (ignored if type is not iscsi)
    # targetPortal: 1.2.3.4:3260
    # iqn: iqn.2001-04.com.example:storage.kube.sys1.xyz
    # lun: 0
    # fsType: ext4
    # secretRef: "" # Name of secret for CHAP authentication

    # -- Node selector configuration.
    # See https://kubernetes.io/docs/concepts/scheduling-eviction/assign-pod-node/
nodeSelector: {}

# -- Tolerations configuration.
# See https://kubernetes.io/docs/concepts/scheduling-eviction/taint-and-toleration/
tolerations: []

# -- Affinity configuration.
# See https://kubernetes.io/docs/concepts/scheduling-eviction/assign-pod-node/#affinity-and-anti-affinity
affinity: {}

# -- Environment variables passed directly to the container.
# See https://kubernetes.io/docs/tasks/inject-data-application/define-environment-variable-container/
# Placeholder: Add common env vars like TZ, PUID, PGID if applicable.
env: {}
  # TZ: Europe/London
  # PUID: 1000
  # PGID: 1000
  # UMASK: "002"

# -- Environment variables sourced from ConfigMaps or Secrets.
# See https://kubernetes.io/docs/tasks/configure-pod-container/configure-pod-configmap/#configure-all-key-value-pairs-in-a-configmap-as-container-environment-variables
envFrom: []
# - secretRef:
#     name: my-secret
# - configMapRef:
#     name: my-configmap

# -- Application specific configuration (non-sensitive).
# Placeholder: Structure this section based on how the application is configured (env vars, config file).
appConfig: {}
  # Example for env var based config:
  # SOME_SETTING: "value"
  # ANOTHER_SETTING: true
  # Example for file based config (used by helper to render file):
  # section:
  #   key: value

# -- Application specific configuration (sensitive).
# Placeholder: Structure this section for sensitive values (API keys, passwords).
secretConfig: {}
  # -- Set to the name of an existing secret containing the full config file content. If set, the chart will not render its own config.
  # existingSecretName: ""
  # -- The key within the existing secret that holds the config file content.
  # existingSecretKey: "config.yaml" # Or config.xml, settings.json etc.

  # Example for env var based config:
  # API_KEY: "" # Provide directly (less secure) or use apiKeySecretRef
  # apiKeySecretRef:
  #   name: "" # Name of existing secret
  #   key: ""  # Key in existing secret

  # Example for file based config (used by helper to render file):
  # database:
  #   password: "" # Provide directly (less secure) or use passwordSecretRef
  #   passwordSecretRef:
  #     name: ""
  #     key: ""
