apiVersion: v2
name: prowlarr
description: A Helm chart for Prowlarr
type: application
version: 1.1.3
appVersion: "1.0.0"

keywords:
- prowlarr
- indexer
- torrent
- usenet

home: https://github.com/Prowlarr/Prowlarr
sources:
- https://github.com/Prowlarr/Prowlarr
- https://hub.docker.com/r/linuxserver/prowlarr
