# ------------------------------------------------------------------------------
# Name and fullname override
# ------------------------------------------------------------------------------
# nameOverride: ""
# fullnameOverride: ""

# ------------------------------------------------------------------------------
# Namespace
# ------------------------------------------------------------------------------
namespace: default

# ------------------------------------------------------------------------------
# Image configuration
# ------------------------------------------------------------------------------
image:
  repository: lscr.io/linuxserver/prowlarr
  tag: latest
  pullPolicy: IfNotPresent

# ------------------------------------------------------------------------------
# Number of replicas
# ------------------------------------------------------------------------------
replicaCount: 1

# ------------------------------------------------------------------------------
# Additional labels
# ------------------------------------------------------------------------------
labels: {}

# ------------------------------------------------------------------------------
# Environment variables (UMASK, etc.)
# ------------------------------------------------------------------------------
env:
  UMASK: "000"

# ------------------------------------------------------------------------------
# Liveness probe
# ------------------------------------------------------------------------------
livenessProbe:
  enabled: true
  initialDelaySeconds: 30
  periodSeconds: 60
  command: |
    curl --fail localhost:9696/prowlarrkube/api/v3/system/status?apiKey=`IFS=\> && while read -d \< E C; do if [[ $E = "ApiKey" ]]; then echo $C; fi; done < /config/config.xml`

# ------------------------------------------------------------------------------
# Service config
# ------------------------------------------------------------------------------
service:
  type: ClusterIP
  port: 9696

# ------------------------------------------------------------------------------
# Resource requests & limits
# ------------------------------------------------------------------------------
resources:
  limits:
    memory: 512Mi
  requests:
    cpu: 50m
    memory: 128Mi

# ------------------------------------------------------------------------------
# Node scheduling
# ------------------------------------------------------------------------------
nodeSelector: {}
tolerations: []
affinity: {}

# ------------------------------------------------------------------------------
# Persistence for Prowlarr config (/config)
# ------------------------------------------------------------------------------
persistence:
  config:
    enabled: true
    size: 1Gi
    existingClaim: ""
    storageClass: ""

# ------------------------------------------------------------------------------
# Hostname override
# ------------------------------------------------------------------------------
hostname: prowlarr

# ------------------------------------------------------------------------------
# configXml: Template-driven config.xml
# ------------------------------------------------------------------------------
configXml:
  # If non-empty, references an existing secret with key "config.xml".
  # Otherwise, chart creates a secret with the rendered config.xml.
  existingSecret: ""

  bindAddress: "*"
  port: 9696
  sslPort: 9697
  enableSsl: "False"
  launchBrowser: "True"
  apiKey: ""
  authenticationMethod: "External"
  authenticationRequired: "DisabledForLocalAddresses"
  branch: "main"
  logLevel: "info"
  sslCertPath: ""
  sslCertPassword: ""
  urlBase: ""
  instanceName: "Prowlarr"
  updateMechanism: "Docker"

  # Postgres block
  postgres:
    enabled: false
    user: ""
    password: ""
    host: ""
    port: ""
    mainDb: ""
    logDb: ""
