name: Release Charts

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  release:
    permissions:
      contents: write
    runs-on: self-hosted
    steps:
      - name: Helm Publish Action
        uses: huggingface/helm-publish-action@latest
        with:
            workingDirectory: charts
            repository: https://harbor.tf141.me/helm
            username: ${{ secrets.HARBOR_USERNAME }}
            password: ${{ secrets.HARBOR_PASSWORD }}
            # beforeHook: cd subcharts/my-sub-chart && helm dependencies update