name: Release Charts

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - 'charts/**'
      - '.github/workflows/release.yaml'
      - 'README.md'

jobs:
  release:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

      - name: Install Helm
        uses: azure/setup-helm@v3
        with:
          version: 'latest'

      - name: Debug - List charts
        run: |
          echo "Listing charts in the charts directory:"
          ls -la charts/
          for chart in charts/*; do
            if [ -d "$chart" ]; then
              echo "Chart: $chart"
              cat "$chart/Chart.yaml"
              echo "---"
            fi
          done

      - name: Create packages directory
        run: mkdir -p .packages

      - name: Package charts manually
        run: |
          # Package each chart
          for chart in charts/*; do
            if [ -d "$chart" ]; then
              echo "Packaging chart: $chart"
              helm package "$chart" -d .packages/
            fi
          done
          
          # List packaged charts
          echo "Packaged charts:"
          ls -la .packages/

      - name: Checkout gh-pages branch
        uses: actions/checkout@v4
        with:
          ref: gh-pages
          path: gh-pages
          token: "${{ secrets.GH_TOKEN }}"
          
      - name: Copy packages to gh-pages
        run: |
          # Copy packaged charts to gh-pages directory
          cp -r .packages/*.tgz gh-pages/ || echo "No packages to copy"
          
          # List files in gh-pages
          echo "Files in gh-pages directory:"
          ls -la gh-pages/

      - name: Generate index.yaml
        run: |
          cd gh-pages
          
          # Create index.yaml using helm
          echo "Creating index.yaml using helm"
          helm repo index --url https://tomf141.github.io/helmcharts/ .
          
          # Check the content of index.yaml
          echo "Content of index.yaml:"
          cat index.yaml

      - name: Commit and push gh-pages changes
        run: |
          cd gh-pages
          git add .
          git commit -m "Update Helm repository" || echo "No changes to commit"
          git push

      - name: Create GitHub releases
        run: |
          # For each packaged chart, create a GitHub release
          for package in .packages/*.tgz; do
            if [ -f "$package" ]; then
              # Extract chart name and version
              filename=$(basename "$package")
              chart_name=$(echo "$filename" | cut -d'-' -f1)
              version=$(echo "$filename" | sed "s/$chart_name-//" | sed 's/\.tgz//')
              
              echo "Creating release for $chart_name version $version"
              
              # Create a GitHub release
              gh release create "$chart_name-$version" "$package" \
                --title "$chart_name $version" \
                --notes "Release of $chart_name version $version" \
                --repo "TOMF141/helmcharts"
            fi
          done
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
