name: Release Charts

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - 'charts/**'
      - '.github/workflows/release.yaml'
      - 'README.md'

jobs:
  release:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

      - name: Install Helm
        uses: azure/setup-helm@v3
        with:
          version: 'latest'

      - name: Debug - List charts
        run: |
          echo "Listing charts in the charts directory:"
          ls -la charts/
          for chart in charts/*; do
            if [ -d "$chart" ]; then
              echo "Chart: $chart"
              cat "$chart/Chart.yaml"
              echo "---"
            fi
          done

      - name: Run chart-releaser
        uses: helm/chart-releaser-action@v1.7.0
        with:
          skip_existing: false
          packages_with_index: true
          charts_dir: charts
          mark_as_latest: false
        env:
          CR_TOKEN: "${{ secrets.GH_TOKEN }}"

      - name: Debug - Check gh-pages branch
        run: |
          # Clone gh-pages branch to check its content
          git clone --branch gh-pages https://github.com/TOMF141/helmcharts.git gh-pages-check
          echo "Content of gh-pages branch:"
          ls -la gh-pages-check/
          if [ -f "gh-pages-check/index.yaml" ]; then
            echo "index.yaml exists in gh-pages branch"
            cat gh-pages-check/index.yaml | head -20
          else
            echo "index.yaml DOES NOT exist in gh-pages branch"
          fi

      - name: Ensure index.yaml exists
        if: ${{ always() }}
        run: |
          # If index.yaml doesn't exist in gh-pages branch, create it manually
          if [ ! -f "gh-pages-check/index.yaml" ]; then
            echo "Creating index.yaml manually"
            
            # Checkout gh-pages branch
            git clone --branch gh-pages https://github.com/TOMF141/helmcharts.git gh-pages
            cd gh-pages
            
            # Configure git
            git config user.name "$GITHUB_ACTOR"
            git config user.email "$GITHUB_ACTOR@users.noreply.github.com"
            
            # Create index.yaml if it doesn't exist
            if [ ! -f "index.yaml" ]; then
              # Find all .tgz files in the directory
              echo "Looking for chart packages (.tgz files)"
              ls -la *.tgz || echo "No .tgz files found"
              
              # Create index.yaml using helm
              echo "Creating index.yaml using helm"
              helm repo index --url https://tomf141.github.io/helmcharts/ .
              
              # Commit and push
              git add index.yaml
              git commit -m "Add index.yaml" || echo "No changes to commit"
              git push https://$GITHUB_ACTOR:${{ secrets.GH_TOKEN }}@github.com/TOMF141/helmcharts.git gh-pages
            fi
          fi
